#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA0WsKyDPADLjeGciPbUN3vWlVa4xKysNgNL0/I7B1SKwu/nwW
    A8/kOFY/VVGuESFByk+adxDLJBGyq9JAikOz05ASCAwr/o+VQ69Gmw0qbgGV89s/
    v5n685dZM93BFto0zI5c9/7+0tMibjlZNfJF1MG/uvMLNdSPWHu5q6siDRNoHZLX
    9cSNZvo8GZtT+SYnNNUrnjYa2ouIza3FcVIMUnbnIrE8hNmlzUglyDhq8dOXu8Pu
    qEqHVvhgH6MNC0tAcVMaqJ1zctnAo5eNO1BrZKjTJDKAD5UdwybkcR1TDWorhN6p
    I0wUPGSg8GKeZGeUVyPaz1md6M1p7w2laBwjWQIDAQABAoIBAQCl8PcjOvaUXi0I
    K0eToiGQwpXAWfOuBfEG+Wq9wga9pkq6tuLO9H34MkePOOEAi+TRBhD1BiaiFzAI
    PNuNdCZbn07ad6Ko3We+sXX2SRF1B+aly/cQwVf8i9JQagimLhQmfyymCrYrosgm
    pWTOfYLeGwTtg8c/SYao66ltoXai+m09/g80URRSwki72sO4I2F8Z7DlNfAJCyxq
    eTv+xt1L5b8Aos2TD1V54jCDsCnqoifzAiAoUTiqooE+LWmNEndgY0SvzP+RkZOT
    TlXfIATVcfstfevYhhVdlq9D+CPViU0aQR3Kr3nyxZpfzEfs16rHpKgdpvdXdG9j
    2z8Or+sNAoGBAPUFOXDheTXedUxeSTcCT2KTOZ030Xy7uklqjrqtQSZgv6fwKF9x
    Gtyix+aCdZSJWIrTuZEVmzU35xixRHT22NqlQqON0bsrV81Fez1cwsxpTkY4LjPW
    KDe1Q8Gdj9ozaNTdl/Dtxx83CmuoUDXBsqGH+xOieR+CORJXO0W1iKkzAoGBANrN
    ZxskPsIlnQUnuHlNJrBcm14Qx/uWBj0dyvcRK71YVJ2VOf5bj3V1xJ0zuaaSdf/m
    uVJgKgxzp2qETFOEL7ou3Ey27FtlyNzM53m4M4mR+qbLkIsxbMpuJw/dJMce5+TB
    vMOT5oflzNNyRCZixY2kXjihAisCW0NL33jkprlDAoGAIKRoiaRQPJ/9aoYpJN32
    64AHre1QyFhOMhezGiWYx18eSWZSSpzL4lcBYLFCrt45YI1ibHS/b7CZ5g0/vIFi
    VIatwRJUvaXBlcRK7drczNS+q9YyOY+vXfSVKUcvcfdlYO6AnoVfAMaZacxLm03J
    2YE/Ltd3YX480jey2s+bfEcCgYBqKTsbqixhGsri03DoOgzJiUVBELdXVGVWhfwS
    gFxOlGsJwnvO9DHY9fkdpRkwvuNN9G56j3oXbI4QWnyGER7vIQl2l1J6zhn1N94f
    6sXmu9N31lEdmC+G0IdXZR8RFefB0FZ8NmimC1OkTE7QqR/dJ6EnrMdWguAw+MFG
    8PoL7QKBgQCTOfsth46lzPY99yW4irqzCCH536Fr94Pa3OWxjWmnJa5vX0/aVO49
    JCwUvdXyU3I0iVqRqVTQkk5ekKf98b5JAYFhgt/q2vl8gM63XaGBgBciZsOtxy5x
    inkNRsyWoH1KGT0Iv/+IQJM4IcBCBdtmYsrQOF3IouvXPTPIzbUNKQ==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/pakchee_release.key
      iv_filename:  /etc/rails/keys/pakchee_release.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAt4JsaVm0Uc0jbHEWctpbWSRqDr77EGFx1c8Qfa/T3RWMeOs3
    KnbQl5tf8YJXVE16sZDEbtn2uJf5+KLeNkM/RLd2sK/mmEsZkRT2BaTkQ2P9Uo4l
    HSCMWvqJfinxN1xHAORSTUQ/mBFkIEMtgA3QWDYAo9zb0OfiDZmw2G8C5CSfgA6t
    QRjrXGojsS1wGX+JyHAZJ4Ox4Su9nLvgo4Nf5tQupf0IMluMa6l/YSLXBOtjh0BS
    tUUs+wMRaTLn6D8y6y6NvzDagOPDORHxGCHQqKWO7H5aHNTDj//TCvvma/X4IzV1
    PTTPU4S3EqVcXXiC1mlhsNRIF68eoflCCRpqawIDAQABAoIBAQCL00TnwQI0kio7
    pq+EM/0Gn0hwk/SZNqaWU4AtRJwaCSFPwWn3YTDvU+R3EOmZwq+KPNRv4oSrgqFl
    YjQPBI5gvaoiVuVNhWulsGMFSe7jqnyLOuPsnbBUYjIBf9PcauNvOom7dhU+uYGh
    U46H0/68N+mk8dRMCWOlGUY2o9+AFVyRMIjTVXzXlEd5spDf8Moi0G4vIEaGIJEW
    kL7RpBkXo4WTXb2OGFfktJYs3YjPXh4u9U9zcASk2ffB+e4s0R2HFi4QQ5WmIZLh
    dilCGrWpPpvOEBZyNoL5KuLbDZGtdiH60atkesGS5rG0BBMIGLRCcZj6sHD0pDar
    7E2etKyBAoGBAOioV8e7cnmAv7Ugw5NW32BToT2lumSn9ortHF+0qq4YmmFmbbGI
    SGFA5Oob1ohqcl5eqWU2wpifRLwJ9r02iRibzqtUnHqDskBY50Awws0idfzVK4lN
    ugYSOzv5H0c1zbkGdQp53rHff+pTH8ZpxaEb0E1sylM02wEAWBj3KyOtAoGBAMnr
    vk87ghtWNJEbZPf6zeFWfJTNv9b+HQuwBhbcyTgFMywIqw7p8S34li7lZE+vhIQl
    8mTLssTPZ+WCvkH0ZrtIdyczx0g75858tMQjJaNz31MH7IHjoFUTOnr8nXq8ZF+r
    3dUJMK49RAR4YGRtsRiL5U3Iyf/Z8YE1gV4qcsl3AoGBAMhXfg89+JtsJKjiJ8eO
    fRfDrAsb1N+sSv7ioxY+yuLTyMyqmTbQ9hLZAMYfZqNdllJxDUlc2ED4lQWfRts0
    ROXt9Q9P8tcE5M/IPonl8zkVvagUIENBrThhJqTEJwz45ce4Kbz1qLBelxW+spP2
    rPnIq5ygW7E+yH+aPkJxRLKZAoGAQTs7e/VJjvNGgCpNcB9CK635CUl+1EG7uG7h
    SLmC9+oWIf+a43KIS8WnHvdUdLnLIbXwnMeBtTsb4XVfaYc/OPmsJKoBk0BnHroC
    2+pO2oMwfm5s5XlX7qQLnHfHmEMMWiv3uj8BzwhT1O3elhMpxzhKl9pqB5GtB4T1
    iipEcvkCgYB3ltBSBf7D0TExXbCK87Con9ZuhNMvy5LoqA6h6gsWzROvB7xYDN8U
    sRwvpPJ7J2Lt4rkBmKjnB/T2wN8ZuhXSf3rbd5QT/dShnfkYt+TpY0hGiMrSkNCH
    93zmg6/beRukQXOmeLO/Upa6BDTNIHo/8XBAK3B1PYK8Qz9cvrhaDg==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/pakchee_production.key
      iv_filename:  /etc/rails/keys/pakchee_production.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1
