#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEApC/PMpIfHITJ0X2dON19VdltSCoxJqQ9bu/zIExWgs5dq1LL
    FDrD8aruiq5v6fyA8vaviuHtGoiyfBtU2anP1nw7IDcwXUXstrMeMgDl16WmjjQj
    aFOko7KZTNqdAO/Oe0P5Tsp5watJlYxSSxlOYleZy/pKCszWutmITtFtZ7/DP83e
    v4ekN6umix8sM6gRyMV50B5RkiHJdo48JHr9BVIqTcuj9U6xtokPHjJM2Dzll7zg
    cKs79y0Adr44n9y8qEq7JrtmsLnrHoc9cxItLCFfe4GP+MSfzQyOAGtQT+eZAzGe
    Vkp4kP2jTdhwPFPeYuIiagZfbU7BUdS3UAvqIwIDAQABAoIBAQCgusDus8dLJt9f
    esYYLhQNn+1wkQVO28fcO4BaJQEnypg+KK3vntvFUF13W+7pNCyULVSJ9EQmDp4U
    CrmU3708Lp+/GOf614I1FMJBl0lqQ5r6aSYkcoWhTyzt5LGAgkIzv8ZnEKYDJwjB
    Iv5I0HxAn5tK6TnkusSXZG8hIbolri10rf9Q5FJ1uYwYZjL8UNb4Xk0RuPyiGFcq
    e9NsYffy21EOkys7Drner8XdbmHnChtcpwxCvPEYhR3Ala1IKIDrsK7ZmsM3QkPX
    OlC1hhiNPACfucUaHue+TWxgogpFEHr5k/sE6kr5xbSruVoUjoCi+a7vWI9ISTIi
    26aOcAw5AoGBANnQSyllKrgleWtvpp/pigXpTOEG8XKp0EWil1xamhXyzQJi/+eK
    RwBVMB9plajpC0ZbE4fokW/AcTAf0poByIZJUiIZPuqogO2T+mi2cwmS9HbvPD6a
    bCf1oJ/yEvbIYZGu2kw6xZlz/v5uYmkUhHuF1LoDTWTgGn+/z+jkO33HAoGBAMD4
    ryvd37IpNCisOP2Jo2PfSlo+QHklEcpMwIgnnGvZ8BkR7UxnakNsohYxvGav2WSR
    4PpKq7BApwgesU6jazDR3/K7RgPMigLgzk+FLrLWb1eMeQMAT+37m7Clfh8XopED
    9V3b7QAi0E7UizJhv+hKTpy6kSFE62ay94BWGuDFAoGAdPHb2Q7jP9mG9oMM0GEA
    ZSocx9kFe83m7+xbHg/bGRuyrKxgv31Dn88dNlBnNThigFTYCKl6pKiLXQ5I8b0x
    X8AwI/SwDieIiYZg9SW4YBSRwuWxz97zYQUFR7seKXfuwtxBgpovi7N23j6AAfEt
    LHDvhSvOuvGD6MEgrOcVdfMCgYBpKh4tBenXKmVmlRUp90y4LQRUUgDJBM7BNTrn
    +M5iaI9U2lQ8g0+CFz3uYoSOYd9T07yMKw2OLG3bGv7+IElWfcpSeoUZpOrBzsog
    xDBC/mIHkGKSpCTrSWf7yPUG9NZ/uWyLDkQHAvILRAHoHyV67qQQ/gwB2ZGAkqAX
    rNVREQKBgQCEy/ju/AqkHvOwn6Es/AkINeJxaiImi5HGLfJIm7UhOWTldP+G2QVL
    BZMLhTh7TyVMdywLQhSzt/W+IOGqhuDODpoq348k6KYw9ZGY2PlCPNznNI/+sS+G
    WkOeANN3pzYXEo3cG84NnJ5htEdWQrG4y9jEMn0MkMorOmzZ9wUyDQ==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key: <%= ENV['KEY'] %>
      iv:  <%= ENV['IV'] %>
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1
